name: bootcamp_team_83_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  camera: ^0.10.0+6
  animated_text_kit: ^4.2.1
  flutter_code_editor: ^0.3.2
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  image_picker: ^0.8.5+3  
  lottie: ^3.0.1
  shared_preferences: ^2.2.3
  stacked: ^3.4.0
  stacked_services: ^0.9.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/chapters/
    - assets/achievements/
    - assets/pathway_backgrounds/
    - assets/pathway_items/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/uygulama_icon.png"
  adaptive_icon_background: "#FFFFFF" # veya şeffaf arka plan için "translucent"
  adaptive_icon_foreground: "assets/uygulama_icon.png"